applications/sitecomponents/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = 'sitecomponents'

urlpatterns = [
    path('', views.landing, name='landing'),  # Asigna la vista home a la URL raíz
    path('intro/', TemplateView.as_view(template_name='views/intro.html'), name='intro'),
]

buildguide/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions


schema_view = get_schema_view(
   openapi.Info(
      title="Project API",
      default_version='v1',
      description="API documentation for Project App",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@yourproject.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts', include('applications.posts.urls')),
    path('projects/', include('applications.projects.urls')),
    path('properties/', include('applications.properties.urls')),
    path('budgets/', include('applications.budgets.urls')),
    path('architecture-projects/', include('applications.architecture_projects.urls')),
    path('', include('applications.sitecomponents.urls')),
    path('accounts/', include('allauth.urls')),
    re_path(r'^login/$', RedirectView.as_view(url='/accounts/login/', permanent=True)),
    re_path(r'^logout/$', RedirectView.as_view(url='/accounts/logout/', permanent=True)),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/components/buttons/GoToDashboard1.html
<!-- action -->
<div class="max-w-80 mx-auto flex flex-row gap-3 justify-center items-center">
    <a href="{% url 'sitecomponents:intro' %}" class="py-2.5 px-5 inline-flex items-center justify-center gap-2 mb-3 rounded leading-5 text-gray-100 bg-indigo-500 border border-indigo-500 hover:text-white hover:bg-indigo-600 hover:ring-0 hover:border-indigo-600 focus:bg-indigo-600 focus:border-indigo-600 focus:outline-none focus:ring-0">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-link-45deg" viewBox="0 0 16 16">
        <path d="M4.715 6.542 3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1 1 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4 4 0 0 1-.128-1.287z"/>
        <path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 1 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 1 0-4.243-4.243z"/>
      </svg>
      Tablero de Documentación
    </a>
  </div>
<!-- End Buttons -->