applications/properties/urls.py
from django.urls import path
from .views import (
    PropertyCreateView,
    PropertyListView,
    PropertyDetailView,
    PropertyUpdateView,
    PropertyDeleteView
)

app_name = 'properties'

urlpatterns = [
    path('properties/', PropertyListView.as_view(), name='list'),
    path('properties/create/', PropertyCreateView.as_view(), name='create'),
    path('properties/<int:pk>/', PropertyDetailView.as_view(), name='detail'),
    path('properties/<int:pk>/update/', PropertyUpdateView.as_view(), name='update'),
    path('properties/<int:pk>/delete/', PropertyDeleteView.as_view(), name='delete'),
]

buildguide/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions


schema_view = get_schema_view(
   openapi.Info(
      title="Project API",
      default_version='v1',
      description="API documentation for Project App",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@yourproject.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts', include('applications.posts.urls')),
    path('projects/', include('applications.projects.urls')),
    path('properties/', include('applications.properties.urls')),
    path('budgets/', include('applications.budgets.urls')),
    path('architecture-projects/', include('applications.architecture_projects.urls')),
    path('', include('applications.sitecomponents.urls')),
    path('accounts/', include('allauth.urls')),
    re_path(r'^login/$', RedirectView.as_view(url='/accounts/login/', permanent=True)),
    re_path(r'^logout/$', RedirectView.as_view(url='/accounts/logout/', permanent=True)),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

applications/properties/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from applications.regioncomuna.models import Region, Comuna


# Create your models here.

class Property(models.Model):
    name = models.CharField(max_length=200, verbose_name=_("Nombre de la Propiedad"))
    rol = models.CharField(max_length=100, verbose_name=_("Rol de la Propiedad"))
    description = models.TextField(verbose_name=_("Descripción"))
    owner = models.ForeignKey('users.User', on_delete=models.SET_NULL, null=True, verbose_name=_("Propietario"))
    address = models.CharField(max_length=255, verbose_name=_("Dirección"))
    region = models.ForeignKey(Region, on_delete=models.SET_NULL, null=True, verbose_name=_("Región"))
    comuna = models.ForeignKey(Comuna, on_delete=models.SET_NULL, null=True, verbose_name=_("Comuna"))
    localidad = models.CharField(max_length=100, blank=True, null=True, verbose_name=_("Localidad"))
    block = models.CharField(max_length=100, blank=True, null=True, verbose_name=_("Cuadra"))
    allotment = models.CharField(max_length=100, blank=True, null=True, verbose_name=_("Lote"))
    neighborhood = models.CharField(max_length=100, blank=True, null=True, verbose_name=_("Población, Loteo, Villa"))
    subdivision_plan = models.CharField(max_length=255, blank=True, null=True, verbose_name=_("Plano de loteo N°"))

    def __str__(self):
        return self.name + " - " + self.rol

    class Meta:
        verbose_name = _("Propiedad")
        verbose_name_plural = _("Propiedades")


class BuildingPermit(models.Model):
    TYPE_CHOICES = (
        ('Obra Menor', 'Obra Menor'),
        ('Anteproyecto', 'Anteproyecto'),
        ('Obra Nueva', 'Obra Nueva')
    )

    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='building_permit')
    permit_date = models.DateField(verbose_name=_("Fecha de Permiso"))
    permit_number = models.CharField(max_length=100, verbose_name=_("Número de Permiso"))
    file = models.FileField(upload_to='permits/', null=True, blank=True, verbose_name=_("Archivo de Permiso"))
    land_area = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name=_("Superficie Permiso"))
    type = models.CharField(max_length=20, choices=TYPE_CHOICES, default='Construcción', verbose_name=_("Tipo de Permiso"))
    permit_comment = models.CharField(max_length=255, blank=True, null=True, verbose_name=_("Comentario de Permiso"))

    def __str__(self):
        return self.property.name + " - " + _("Permiso")

    class Meta:
        verbose_name = _("Permiso de la Propiedad")
        verbose_name_plural = _("Permisos de la Propiedad")

        ordering = ['permit_date']


class BuildingReception(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='bulding_reception')
    reception_number = models.CharField(
        max_length=100, verbose_name=_("Número de Recepción"))
    reception_date = models.DateField(verbose_name=_("Fecha de Recepción"))
    partial_reception = models.BooleanField(default=False, verbose_name=_("Recepción Parcial"))
    building_permit = models.ForeignKey(BuildingPermit, on_delete=models.SET_NULL, null=True, blank=True, verbose_name=_("Permiso de Construcción"))
    file = models.FileField(upload_to='receptions/', null=True, blank=True, verbose_name=_("Archivo de Recepción"))
    land_area = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True, verbose_name=_("Superficie Terreno"))
    reception_comment = models.CharField(max_length=255, blank=True, null=True, verbose_name=_("Comentario de Recepción"))

    def __str__(self):
        return self.property.name + " - " + _("Recepción")

    class Meta:
        verbose_name = _("Recepción de la Propiedad")
        verbose_name_plural = _("Recepciones de la Propiedad")

        ordering = ['reception_date']


class WaterCertificate(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='water_certificate')
    certificate_number = models.CharField(max_length=100, verbose_name=_("Número de Certificado"))
    certificate_date = models.DateField(verbose_name=_("Fecha de Certificado"))
    file = models.FileField(upload_to='certificates/', null=True, blank=True, verbose_name=_("Archivo de Certificado"))
    certificate_comment = models.CharField(max_length=255, blank=True, null=True, verbose_name=_("Comentario de Certificado"))

    def __str__(self):
        return self.property.name + " - " + _("Certificado de Agua")

    class Meta:
        verbose_name = _("Certificado de Agua")
        verbose_name_plural = _("Certificados de Agua")

        ordering = ['certificate_date']


class ElectricCertificate(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='electric_certificate')
    certificate_number = models.CharField(max_length=100, verbose_name=_("Número de Certificado"))
    certificate_date = models.DateField(verbose_name=_("Fecha de Certificado"))
    file = models.FileField(upload_to='certificates/', null=True, blank=True, verbose_name=_("Archivo de Certificado"))
    certificate_comment = models.CharField(max_length=255, blank=True, null=True, verbose_name=_("Comentario de Certificado"))

    def __str__(self):
        return self.property.name + " - " + _("Certificado Eléctrico")

    class Meta:
        verbose_name = _("Certificado Eléctrico")
        verbose_name_plural = _("Certificados Eléctricos")

        ordering = ['certificate_date']


class GasCertificate(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='gas_certificate')
    certificate_number = models.CharField(max_length=100, verbose_name=_("Número de Certificado"))
    certificate_date = models.DateField(verbose_name=_("Fecha de Certificado"))
    file = models.FileField(upload_to='certificates/', null=True, blank=True, verbose_name=_("Archivo de Certificado"))
    certificate_comment = models.CharField(max_length=255, blank=True, null=True, verbose_name=_("Comentario de Certificado"))

    def __str__(self):
        return self.property.name + " - " + _("Certificado de Gas")

    class Meta:
        verbose_name = _("Certificado de Gas")
        verbose_name_plural = _("Certificados de Gas")

        ordering = ['certificate_date']


class OtherCertificate(models.Model):
    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='other_certificate')
    certificate_name = models.CharField(max_length=100, verbose_name=_("Nombre del Certificado"))
    certificate_number = models.CharField(max_length=100, verbose_name=_("Número de Certificado"))
    certificate_date = models.DateField(verbose_name=_("Fecha de Certificado"))
    file = models.FileField(upload_to='certificates/', null=True, blank=True, verbose_name=_("Archivo de Certificado"))
    certificate_comment = models.CharField(max_length=255, blank=True, null=True, verbose_name=_("Comentario de Certificado"))

    def __str__(self):
        return self.property.name + " - " + self.certificate_name

    class Meta:
        verbose_name = _("Otros Certificados")
        verbose_name_plural = _("Otros Certificados")

        ordering = ['certificate_date']

        unique_together = ('property', 'certificate_name')


class CountyRecorder(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("Nombre del Conservador"))
    comuna = models.ForeignKey(Comuna, on_delete=models.CASCADE, verbose_name=_("Comuna"))

    def __str__(self):
        return 'Conservador de Bienes Raíces de ' + self.comuna.comuna


class OwnershipCertificate(models.Model):
    TYPE_CHOICES = (
        ('Hipotecas y Gravámenes', 'Hipotecas y Gravámenes'),
        ('Propiedad',  'Propiedad'),
        ('Prohibiciones', 'Prohibiciones')
    )

    property = models.ForeignKey(Property, on_delete=models.CASCADE, related_name='ownership_certificate')
    county_recorder = models.ForeignKey(CountyRecorder, on_delete=models.CASCADE, verbose_name=_("county_recorder"))
    type = models.CharField(max_length=30, choices=TYPE_CHOICES, default='Propiedad', verbose_name=_("Tipo de Certificado"))
    leaves = models.CharField(max_length=100, verbose_name=_("Fojas"))
    number = models.CharField(max_length=100, verbose_name=_("Número"))
    year = models.CharField(max_length=100, verbose_name=_("Año"))
    file = models.FileField(upload_to='certificates/', null=True, blank=True, verbose_name=_("Archivo de Certificado"))
    certificate_comment = models.CharField(max_length=255, blank=True, null=True, verbose_name=_("Comentario de Certificado"))

    def __str__(self):
        return self.property.name + " - " + _("Certificado de Patente")

    class Meta:
        verbose_name = _("Certificado de Patente")
        verbose_name_plural = _("Certificados de Patente")

        ordering = ['year']

applications/properties/forms.py
from django import forms
from .models import Property

class PropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = '__all__'  # Puedes especificar los campos o simplemente usar '__all__' para incluir todos los campos del modelo.
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
            # Añade más widgets según necesites para mejorar la UI
        }

applications/properties/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Property
from .forms import PropertyForm


class PropertyCreateView(LoginRequiredMixin, CreateView):
    model = Property
    form_class = PropertyForm
    template_name = 'apps/properties/create_property_form.html'
    success_url = reverse_lazy('properties:list')

    def post(self, request, *args, **kwargs):
        print("POST data Property:", request.POST)
        return super().post(request, *args, **kwargs)


class PropertyListView(LoginRequiredMixin, ListView):
    model = Property
    template_name = 'apps/properties/properties_list.html'
    context_object_name = 'properties'


class PropertyDetailView(LoginRequiredMixin, DetailView):
    model = Property
    template_name = 'apps/properties/property_detail.html'
    context_object_name = 'property'


class PropertyUpdateView(LoginRequiredMixin, UpdateView):
    model = Property
    form_class = PropertyForm
    template_name = 'apps/properties/property_update.html'
    success_url = reverse_lazy('properties:list')


class PropertyDeleteView(LoginRequiredMixin, DeleteView):
    model = Property
    template_name = 'apps/properties/property_delete.html'
    success_url = reverse_lazy('properties:list')
    context_object_name = 'property'

templates/apps/properties/create_property.html
{% extends 'components/layouts/applayout.html' %}
{% block content %}
<h2>Create Property</h2>

{% endblock %}

templates/apps/properties/create_property_form.html
{% block content %}

<div class="flex-shrink max-w-full px-4 w-full mb-6">
                <div class="p-6 bg-white dark:bg-gray-800 rounded-lg shadow-lg h-full">
                    <!-- Inicio formulario creación de Propiedad -->
                    <form method="post" action="{% url 'properties:create' %}" class="flex flex-wrap flex-row -mx-4">
                        {% csrf_token %}
                        <!-- Campo título propiedad -->
                        <div class="flex-shrink max-w-full px-4 w-full mb-4">
                            <label for="input_property_title" class="inline-block mb-2">
                                Título propiedad
                            </label>
                            <input type="text"
                                   name="name"
                                   class="w-full leading-5 relative py-2 px-4 rounded text-gray-800 bg-white border border-gray-300 overflow-x-auto focus:outline-none focus:border-gray-400 focus:ring-0 dark:text-gray-300 dark:bg-gray-700 dark:border-gray-700 dark:focus:border-gray-600"
                                   id="input_property_title"
                                   placeholder="Ingrese el nombre de la propiedad">
                        </div>

                        <!-- Campo descripción proyecto -->
                        <div class="flex-shrink max-w-full px-4 w-full mb-4">
                            <label for="input_property_des" class="inline-block mb-2">Descripción de propiedad</label>
                            <textarea type="text"
                                      name="description"
                                      class="w-full leading-5 relative py-2 px-4 rounded text-gray-800 bg-white border border-gray-300 overflow-x-auto focus:outline-none focus:border-gray-400 focus:ring-0 dark:text-gray-300 dark:bg-gray-700 dark:border-gray-700 dark:focus:border-gray-600"
                                      id="input_property_des">
                            </textarea>
                        </div>

                        <div class="flex-shrink max-w-full px-4 w-full">
                            <button type="submit"
                                    class="py-2 px-4 block lg:inline-block text-center rounded leading-5 text-gray-100 bg-indigo-500 border border-indigo-500 hover:text-white hover:bg-indigo-600 hover:ring-0 hover:border-indigo-600 focus:bg-indigo-600 focus:border-indigo-600 focus:outline-none focus:ring-0">
                                Guardar Propiedad
                                <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor"
                                     class="inline-block ltr:ml-1 rtl:mr-1 bi bi-plus-lg" viewBox="0 0 16 16">
                                    <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"></path>
                                </svg>
                            </button>
                        </div>
                    </form>

                </div>
            </div>

{% endblock %}

templates/apps/properties/properties_list.html
{% extends 'components/layouts/applayout.html' %}
{% block content %}
<h2>Properties List</h2>
{% for property in properties %}
  <p>{{ property.name }} - <a href="{% url 'properties:detail' property.id %}">View</a></p>
{% endfor %}
{% endblock %}

templates/apps/properties/property_delete.html
{% extends 'components/layouts/applayout.html' %}
{% block content %}
<h2>Delete Property</h2>
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete "{{ property.name }}"?</p>
    <button type="submit">Delete</button>
</form>
{% endblock %}

templates/apps/properties/property_detail.html
{% extends 'components/layouts/applayout.html' %}
{% block content %}

<main class="pt-6 -mt-2">
        <div class="mx-auto py-2 sm:px-2">
          <!-- row -->
          <div class="flex flex-wrap flex-row">
            <div class="flex-shrink max-w-full px-4 w-full">
              <p class="text-xl font-bold mt-3 mb-5">{{ property.name }} - {{ property.rol }}</p>
            </div>
            <div class="flex-shrink max-w-full px-4 w-full mb-6">
              <div class="p-6 bg-white dark:bg-gray-800 rounded-lg shadow-lg h-full">
                <form class="flex flex-wrap flex-row -mx-4">
                  <div class="flex-shrink max-w-full px-4 w-full mb-4">
                    <label for="inputtitle" class="inline-block mb-2">Título proyecto</label>
                    <input type="text"
                           class="w-full leading-5 relative py-2 px-4 rounded text-gray-800 bg-white border border-gray-300 overflow-x-auto focus:outline-none focus:border-gray-400 focus:ring-0 dark:text-gray-300 dark:bg-gray-700 dark:border-gray-700 dark:focus:border-gray-600"
                           id="inputtitle"
                           placeholder="{{ property.name }}"
                           aria-label="Disabled input example"
                           disabled>
                  </div>
                  <div class="flex-shrink max-w-full px-4 w-full mb-4">
                    <label for="inputdes" class="inline-block mb-2">Descripción de proyecto</label>
                    <textarea type="text"
                              class="w-full leading-5 relative py-2 px-4 rounded text-gray-800 bg-white border border-gray-300 overflow-x-auto focus:outline-none focus:border-gray-400 focus:ring-0 dark:text-gray-300 dark:bg-gray-700 dark:border-gray-700 dark:focus:border-gray-600"
                              id="inputdes"
                              placeholder="{{ property.description }}"
                              aria-label="Disabled input example"
                              disabled>
                    </textarea>
                  </div>
                  <div class="flex-shrink max-w-full px-4 w-full md:w-1/3 mb-4">
                    <label for="inputaddress" class="inline-block mb-2">Dirección</label>
                    <input type="text"
                           class="w-full leading-5 relative py-2 px-4 rounded text-gray-800 bg-white border border-gray-300 overflow-x-auto focus:outline-none focus:border-gray-400 focus:ring-0 dark:text-gray-300 dark:bg-gray-700 dark:border-gray-700 dark:focus:border-gray-600"
                           id="inputaddress"
                           placeholder="{{ property.address }}"
                           aria-label="Disabled input example"
                           disabled>
                  </div>
                  <div class="flex-shrink max-w-full px-4 w-full md:w-1/2 mb-4">
                    <label for="inputtask" class="inline-block mb-2">Total Task</label>
                    <input type="text" class="w-full leading-5 relative py-2 px-4 rounded text-gray-800 bg-white border border-gray-300 overflow-x-auto focus:outline-none focus:border-gray-400 focus:ring-0 dark:text-gray-300 dark:bg-gray-700 dark:border-gray-700 dark:focus:border-gray-600" id="inputtask">
                  </div>
                  <div class="flex-shrink max-w-full px-4 w-full mb-4">
                    <label for="imageSingle" class="inline-block mb-2">Thumbnail (80x80 png, gif, svg or jpg)</label>
                    <div id="imageSingle" class="dropzone single-dropzone mb-4">
                      <div class="dz-message" data-dz-message>
                        <div class="pre-upload flex flex-col justify-center">
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="mx-auto text-gray-500 inline-block w-10 h-10 bi bi-cloud-arrow-up" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M7.646 5.146a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L8.5 6.707V10.5a.5.5 0 0 1-1 0V6.707L6.354 7.854a.5.5 0 1 1-.708-.708l2-2z"></path>
                            <path d="M4.406 3.342A5.53 5.53 0 0 1 8 2c2.69 0 4.923 2 5.166 4.579C14.758 6.804 16 8.137 16 9.773 16 11.569 14.502 13 12.687 13H3.781C1.708 13 0 11.366 0 9.318c0-1.763 1.266-3.223 2.942-3.593.143-.863.698-1.723 1.464-2.383zm.653.757c-.757.653-1.153 1.44-1.153 2.056v.448l-.445.049C2.064 6.805 1 7.952 1 9.318 1 10.785 2.23 12 3.781 12h8.906C13.98 12 15 10.988 15 9.773c0-1.216-1.02-2.228-2.313-2.228h-.5v-.5C12.188 4.825 10.328 3 8 3a4.53 4.53 0 0 0-2.941 1.1z"></path>
                          </svg>
                          <div class="py-3"><span>Drag & drop images here</span></div>
                        </div>
                        <div class="pre-upload text-center">
                          <button class="py-1.5 px-3 inline-block text-center rounded leading-normal text-gray-800 bg-gray-100 border border-gray-100 hover:text-gray-900 hover:bg-gray-200 hover:ring-0 hover:border-gray-200 focus:bg-gray-200 focus:border-gray-200 focus:outline-none focus:ring-0 mr-2 dark:bg-gray-300">Browse file</button>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="flex-shrink max-w-full px-4 w-full mb-4">
                    <label for="rangetime" class="inline-block mb-2">Start and End date</label>
                    <div id="rangetime" class="flex flex-col justify-center md:flex-row md:justify-between">
                      <input id="startDate" class="startDate w-full leading-5 relative text-sm py-2 px-4 rounded text-gray-800 bg-white border border-gray-300 overflow-x-auto focus:outline-none focus:border-gray-400 focus:ring-0 dark:text-gray-300 dark:bg-gray-700 dark:border-gray-700 dark:focus:border-gray-600" type="text" name="start">
                      <span class="px-4 text-center">to</span>
                      <input id="endDate" class="endDate w-full leading-5 relative text-sm py-2 px-4 rounded text-gray-800 bg-white border border-gray-300 overflow-x-auto focus:outline-none focus:border-gray-400 focus:ring-0 dark:text-gray-300 dark:bg-gray-700 dark:border-gray-700 dark:focus:border-gray-600" type="text" name="end">
                    </div>
                  </div>
                  <div class="flex-shrink max-w-full px-4 w-full mb-4">
                    <label for="tagsselect" class="inline-block mb-2">Tags Select</label>
                    <input name="selectname" value="" class="tagify-select w-full leading-5 relative text-sm py-2 px-4 rounded text-gray-800 bg-white border border-gray-300 overflow-x-auto focus:outline-none focus:border-gray-400 focus:ring-0 dark:text-gray-300 dark:bg-gray-700 dark:border-gray-700 dark:focus:border-gray-600" id="tagsselect" minlength="2">

                    <div class="relative mt-2">
                      <a href="#">
                        <img class="inline-block rounded-full shadow-xl w-12 h-12 max-w-full ltr:-mr-4 rtl:-ml-4 border-2 bg-gray-300 border-gray-200 transform hover:-translate-y-1" src="../src/img/avatar/avatar2.png" alt="Image Description">
                      </a>
                      <a href="#">
                        <img class="inline-block rounded-full shadow-xl w-12 h-12 max-w-full ltr:-mr-4 rtl:-ml-4 border-2 bg-gray-300 border-gray-200 transform hover:-translate-y-1" src="../src/img/avatar/avatar3.png" alt="Image Description">
                      </a>
                      <a href="#">
                        <img class="inline-block rounded-full shadow-xl w-12 h-12 max-w-full ltr:-mr-4 rtl:-ml-4 border-2 bg-gray-300 border-gray-200 transform hover:-translate-y-1" src="../src/img/avatar/avatar5.png" alt="Image Description">
                      </a>
                    </div>
                  </div>

                  <div class="flex-shrink max-w-full px-4 w-full">
                    <button type="submit" class="py-2 px-4 block lg:inline-block text-center rounded leading-5 text-gray-100 bg-indigo-500 border border-indigo-500 hover:text-white hover:bg-indigo-600 hover:ring-0 hover:border-indigo-600 focus:bg-indigo-600 focus:border-indigo-600 focus:outline-none focus:ring-0">Add new project <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor" class="inline-block ltr:ml-1 rtl:mr-1 bi bi-plus-lg" viewBox="0 0 16 16">
                        <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"></path>
                      </svg></button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </main>

{% endblock %}

templates/apps/properties/property_update.html
{% extends 'components/layouts/applayout.html' %}
{% block content %}
<h2>Update Property</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update</button>
</form>
{% endblock %}