applications/projects/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from .api.viewsets.project_viewset import ProjectViewSet
from .views import *

app_name = 'projects'

router = DefaultRouter()
router.register(r'projects', ProjectViewSet)

urlpatterns = [
    path('projects/', ProjectListView.as_view(), name='project_list'),
    path('projects/create_and_edit/', create_and_edit_project, name='create_and_edit_project'),
    path('projects/<int:pk>/create/', ProjectCreateView.as_view(), name='create_project'),
    path('projects/<int:pk>/', ProjectDetailView.as_view(), name='project_detail'),
    path('projects/<int:pk>/delete/', ProjectDeleteView.as_view(), name='delete_project'),
    path('api/', include(router.urls)),
]

buildguide/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import RedirectView
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from rest_framework import permissions


schema_view = get_schema_view(
   openapi.Info(
      title="Project API",
      default_version='v1',
      description="API documentation for Project App",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@yourproject.com"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('posts', include('applications.posts.urls')),
    path('projects/', include('applications.projects.urls')),
    path('properties/', include('applications.properties.urls')),
    path('budgets/', include('applications.budgets.urls')),
    path('architecture-projects/', include('applications.architecture_projects.urls')),
    path('', include('applications.sitecomponents.urls')),
    path('accounts/', include('allauth.urls')),
    re_path(r'^login/$', RedirectView.as_view(url='/accounts/login/', permanent=True)),
    re_path(r'^logout/$', RedirectView.as_view(url='/accounts/logout/', permanent=True)),
    re_path(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    re_path(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    re_path(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

applications/projects/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel

from applications.users.models import User


class Project(TimeStampedModel):
    project_name = models.CharField(max_length=100, verbose_name=_('Nombre del proyecto'))
    project_description = models.CharField(max_length=1000, verbose_name=_('Descripción'))
    property = models.ForeignKey('properties.Property', on_delete=models.SET_NULL, null=True, blank=True,  verbose_name=_('Propiedad'), related_name='projects')
    project_owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name=_('Creador'))
    is_active = models.BooleanField(default=True, verbose_name=_('Activo'))

    class Meta:
        verbose_name = _('Proyecto')
        verbose_name_plural = _('Proyectos')

    def __str__(self):
        return self.project_name


class ProjectCollaborator(TimeStampedModel):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, verbose_name=_('Proyecto'), related_name='collaborators')
    collaborator = models.ForeignKey('users.User', on_delete=models.CASCADE, verbose_name=_('Colaborador'))
    role = models.ForeignKey('users.Role', on_delete=models.SET_NULL, null=True, verbose_name=_('Rol'))
    can_edit = models.BooleanField(default=False, verbose_name=_('Puede editar'))
    company = models.ForeignKey('users.Company', on_delete=models.SET_NULL, null=True, verbose_name=_('Empresa'), related_name='collaborators')
    is_legal_rep = models.BooleanField(default=False, verbose_name=_('Es representante legal'))

    def __str__(self):
        return f'{self.project.name} - {self.collaborator.name}'

    class Meta:
        verbose_name = _('Colaborador de Proyecto')
        verbose_name_plural = _('Colaboradores de Proyecto')

applications/projects/forms.py
from django import forms
from .models import Project


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['project_name', 'project_description']
        widgets = {
            'project_name': forms.TextInput(attrs={
                'class': 'form-control',
                'id': 'project_name',
            }),
            'project_description': forms.Textarea(attrs={
                'class': 'form-control',
                'id': 'project_description',
            })
        }

applications/projects/views/project_views.py
import json

from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseRedirect, QueryDict
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.decorators.http import require_http_methods
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from applications.projects.models import Project
from applications.projects.forms import ProjectForm
from django.urls import reverse


@login_required
def create_and_edit_project(request):
    new_project = Project(
        project_owner=request.user,
        is_active=True
    )
    new_project.save()
    return redirect(reverse('projects:create_project', kwargs={'pk': new_project.pk}))


class ProjectCreateView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = 'apps/projects/project_create.html'
    context_object_name = 'project'

    def get_object(self):
        # Asegúrate de que el ID del proyecto está siendo capturado como 'pk' en la URL
        return get_object_or_404(Project, pk=self.kwargs.get('pk'))


class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name = 'apps/projects/project_list.html'
    context_object_name = 'projects'

    def get_queryset(self):
        return Project.objects.filter(project_owner=self.request.user)


# Vista de detalle
class ProjectDetailView(LoginRequiredMixin, DetailView):
    model = Project
    template_name = 'apps/projects/project_detail.html'
    context_object_name = 'project'


# Vista para eliminar proyectos
class ProjectDeleteView(LoginRequiredMixin, DeleteView):
    model = Project
    template_name = 'apps/projects/project_confirm_delete.html'
    success_url = reverse_lazy('projects:project_list')
    context_object_name = 'project'

templates/apps/projects/create_project_form.html
{% block content %}
{% load static %}

<div class="flex-shrink max-w-full px-4 w-full mb-6">
    <div class="p-6 bg-white dark:bg-gray-800 rounded-lg shadow-lg h-full">
        <!-- Inicio formulario creación de Proyecto -->
        <div class="flex flex-wrap flex-row -mx-4">
            <!-- Campo título proyecto -->
            <div class="flex-shrink max-w-full px-4 w-full mb-4">
                <div class="flex items-center mb-2">
                    <label for="inputtitle" class="inline-block mb-2">
                        Título proyecto
                        <div x-data="{ tooltips: false }" class="relative inline-block">
                            <button x-on:mouseover="tooltips = true" x-on:mouseleave="tooltips = false"
                                    type="button" class="inline-block">
                                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20"
                                     fill="currentColor" class="bi bi-question-circle" viewBox="0 0 16 16">
                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14m0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16"/>
                                    <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286m1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94"/>
                                </svg>
                            </button>
                            <!-- tooltip area -->
                            <div class="absolute top-auto bottom-full mb-3" x-cloak
                                 x-show.transition.origin.top="tooltips">
                                <div class="w-40 p-3 -mb-1 text-sm leading-tight text-white bg-black rounded-lg shadow-lg text-center">
                                    Título global del proyecto. Ejemplos: 'Proyecto Clínica Salud', 'Casa playa Agustín Miranda'
                                </div>
                                <div class="absolute transform -rotate-45 p-1 w-1 bg-black bottom-0 -mb-2 ltr:ml-6 rtl:mr-6"></div>
                            </div>
                        </div>
                    </label>
                        <div id="saving-indicator-name-{{ project.id }}" class="ml-2" style="display: none;">
                        </div>
                </div>
                <div id="inputtitle-wrapper">
                    <textarea
                           name="project_name"
                           hx-patch="/projects/api/projects/{{ project.id }}/"
                           hx-trigger="keyup changed delay:1s"
                           hx-target="#inputtitle-wrapper"
                           hx-swap="none"
                           class="w-full leading-5 py-2 px-4 rounded text-gray-800 bg-white border border-gray-300 overflow-x-auto focus:outline-none focus:border-gray-400 focus:ring-0 dark:text-gray-300 dark:bg-gray-700 dark:border-gray-700 dark:focus:border-gray-600"
                           id="inputtitle"
                           placeholder="Ingrese el nombre del proyecto">{{ project.project_name }}</textarea>
                </div>

                <div class="flex justify-between items-center mt-2">
                    <div class="flex-grow">
                        <div id="error-inputtitle" class="text-red-500 text-sm" style="min-height: 1em;"></div>
                    </div>
                    <div id="inputtitle-counter" class="text-gray-500 text-sm" style="white-space: nowrap;">0/100 caracteres</div>
                </div>
            </div>

            <!-- Campo descripción proyecto -->
            <div class="flex-shrink max-w-full px-4 w-full mb-4">
                <div class="flex items-center mb-2">
                    <label for="inputdes" class="inline-block mb-2">Descripción de proyecto</label>
                    <div id="saving-indicator-description-{{ project.id }}" class="ml-2" style="display: none;">
                    </div>
                </div>
                <div id="inputdes-wrapper">
                    <textarea name="project_description"
                              hx-patch="/projects/api/projects/{{ project.id }}/"
                              hx-trigger="keyup changed delay:1s"
                              hx-target="#inputdes-wrapper"
                              hx-swap="none"
                              class="w-full leading-5 relative py-2 px-4 rounded text-gray-800 bg-white border border-gray-300 overflow-x-auto focus:outline-none focus:border-gray-400 focus:ring-0 dark:text-gray-300 dark:bg-gray-700 dark:border-gray-700 dark:focus:border-gray-600"
                              id="inputdes"
                              placeholder="Ingrese la descripción del proyecto"
                              style="resize: none; overflow: hidden; min-height: 40px;">{{ project.project_description }}</textarea>
                </div>
                <div class="flex justify-between items-center mt-2">
                    <div class="flex-grow">
                        <div id="error-inputdes" class="text-red-500 text-sm" style="min-height: 1em;"></div>
                    </div>
                    <div id="inputdes-counter" class="text-gray-500 text-sm" style="white-space: nowrap;">0/1000 caracteres</div>
                </div>
            </div>

            <!-- Botón Crear subproyecto Arquitectura-->
            <div class="flex-shrink max-w-full px-4 w-full">
                <button type="button"
                        id="addArchProjectButton"
                        hx-post="/architecture-projects/api/architecture-projects/"
                        hx-include="#hiddenProjectId"
                        hx-target="#responseContainer"
                        hx-swap="outerHTML"
                        hx-trigger="click"
                        class="py-2 px-4 block lg:inline-block text-center rounded leading-5 text-gray-100 bg-indigo-500 border border-indigo-500 hover:text-white hover:bg-indigo-600 hover:ring-0 hover:border-indigo-600 focus:bg-indigo-600 focus:border-indigo-600 focus:outline-none focus:ring-0">
                    Agregar subproyecto de Arquitectura
                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" fill="currentColor"
                         class="inline-block ltr:ml-1 rtl:mr-1 bi bi-plus-lg" viewBox="0 0 16 16">
                        <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"></path>
                    </svg>
                </button>

                <input type="hidden" id="hiddenProjectId" name="project" value="{{ project.id }}">
                <div id="responseContainer">
                    {% include 'apps/architecture_projects/create_architecture_project.html' %}
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock %}

{% block extra_scripts %}
<script src="{% static 'js/utils/setupSpinner.js' %}"></script>
<script src="{% static 'js/utils/setupCharacterCounter.js' %}"></script>
<script src="{% static 'js/utils/autoResizeTextArea.js' %}"></script>
<script>
    setupSpinner('inputtitle', 'saving-indicator-name-{{ project.id }}', 'error-inputtitle');
    setupCharacterCounter('inputtitle', 'inputtitle-counter', 100);
    autoResizeTextarea('inputtitle');
    setupSpinner('inputdes', 'saving-indicator-description-{{ project.id }}', 'error-inputdes');
    setupCharacterCounter('inputdes', 'inputdes-counter', 1000);
    autoResizeTextarea('inputdes');
</script>
<script>
document.body.addEventListener('htmx:afterSwap', function(event) {
    if (event.target.id === 'responseContainer') {
        // Aquí puedes añadir cualquier inicialización necesaria o manipular el DOM como necesites.
        document.getElementById('addArchProjectButton').style.display = 'none';
    }
});
</script>

{% endblock %}

templates/apps/projects/project_confirm_delete.html
{% extends 'components/layouts/applayout.html' %}

{% block content %}
<div class="container">
    <h1>Confirmar eliminación</h1>
    <p>¿Estás seguro que deseas eliminar el proyecto "{{ project.project_name }}"?</p>

    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Eliminar</button>
        <a href="{% url 'projects:project_list' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/apps/projects/project_create.html
{% extends 'components/layouts/applayout.html' %}
{% block content %}

<main class="pt-6 -mt-2">
    <div class="mx-auto py-2 sm:px-2">
        <!-- row -->
        <div class="flex flex-wrap flex-row">
            <div class="flex-shrink max-w-full px-4 w-full">
                <p class="text-xl font-bold mt-3 mb-5">Crear Proyecto</p>
            </div>

            {% include 'apps/projects/create_project_form.html' %}

        </div>
    </div>
</main>

{% endblock %}

templates/apps/projects/project_list.html
{% extends 'components/layouts/applayout.html' %}

{% block content %}


    <div class="mx-auto py-2 sm:px-2">
        <!-- row -->
        <div class="flex flex-wrap flex-row">
            <div class="flex-shrink max-w-full px-4 w-full">
                <p class="text-xl font-bold mt-3 mb-5">Lista de Proyectos</p>
            </div>
            <div class="flex-shrink max-w-full px-4 w-full mb-6">
                <div class="py-4 px-6 bg-white dark:bg-gray-800 rounded-lg shadow-lg h-full">
                    <div class="flex flex-wrap flex-row">
                        <div class="flex-shrink max-w-full w-full">
                            <div class="md:flex md:justify-between">
                                <a href="{% url 'projects:create_and_edit_project' %}"
                                   class="py-2 px-4 block lg:inline-block text-center rounded leading-5 text-gray-100 bg-indigo-500 border border-indigo-500 hover:text-white hover:bg-indigo-600 hover:ring-0 hover:border-indigo-600 focus:bg-indigo-600 focus:border-indigo-600 focus:outline-none focus:ring-0">Crear
                                    Proyecto
                                    <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12"
                                         fill="currentColor"
                                         class="inline-block ltr:ml-1 rtl:mr-1 bi bi-plus-lg"
                                         viewBox="0 0 16 16">
                                        <path d="M8 0a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2H9v6a1 1 0 1 1-2 0V9H1a1 1 0 0 1 0-2h6V1a1 1 0 0 1 1-1z"></path>
                                    </svg>
                                </a>

                                <!-- search -->
                                <div class="relative flex items-center w-full md:w-60 h-full group mt-4 md:mt-0 md:self-center">
                                    <svg class="absolute ltr:left-0 rtl:right-0 z-20 w-4 h-4 ltr:ml-4 rtl:mr-4 text-gray-500 pointer-events-none fill-current group-hover:text-gray-400 block"
                                         xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20">
                                        <path d="M12.9 14.32a8 8 0 1 1 1.41-1.41l5.35 5.33-1.42 1.42-5.33-5.34zM8 14A6 6 0 1 0 8 2a6 6 0 0 0 0 12z"></path>
                                    </svg>
                                    <input type="text"
                                           class="block w-full py-1.5 ltr:pl-10 ltr:pr-4 rtl:pr-10 rtl:pl-4 leading-normal rounded-2xl focus:outline-none bg-gray-100 border border-gray-100 focus:border-gray-200 focus:ring-0 dark:text-gray-400 dark:bg-gray-700 dark:border-gray-700 dark:focus:border-gray-700"
                                           placeholder="Search project">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="flex flex-wrap flex-row">
            {% for project in projects %}
            <!-- project item -->
            <div class="flex-shrink max-w-full px-4 w-full lg:w-1/2">
                <div class="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6 mb-6">
                    <div class="flex flex-row justify-between pb-4">
                        <div class="flex flex-col">
                            <h3 class="text-base font-bold">{{ project.project_name }}</h3>
                        </div>
                        <div x-data="{ open: false }" class="relative">
                            <button @click="open = ! open"
                                    class="text-gray-500 hover:text-gray-600 dark:hover:text-gray-400 transition-colors duration-200 focus:outline-none hover:outline-none">
                                <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                                     class="w-6 h-6 bi bi-three-dots" viewBox="0 0 16 16">
                                    <path d="M3 9.5a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3zm5 0a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3z"></path>
                                </svg>
                            </button>
                            <div x-show="open" @click.away="open = false"
                                 class="origin-top-right absolute ltr:right-0 rtl:left-0 rounded rounded-t-non bg-white dark:bg-gray-800 z-10 border border-gray-200 dark:border-gray-700"
                                 style="min-width: 12rem; display: none;">
                                <a class="block px-3 py-2 hover:bg-gray-100 focus:bg-gray-100 dark:hover:bg-gray-900 dark:hover:bg-opacity-20 dark:focus:bg-gray-900"
                                   href="#">Editar</a>
                                <a class="block px-3 py-2 hover:bg-gray-100 focus:bg-gray-100 dark:hover:bg-gray-900 dark:hover:bg-opacity-20 dark:focus:bg-gray-900"
                                   href="{% url 'projects:delete_project' project.id %}">Eliminar</a>
                            </div>
                        </div>
                    </div>

                    <div class="flex flex-col pb-4">
                        <div class="flex flex-row items-center">
                            <img src="../src/img/brand/logo.png"
                                 class="w-20 h-auto max-w-full ltr:mr-3 rtl:ml-3">
                            <p class="text-sm text-gray-500">{{ project.project_description }} </p>
                        </div>
                    </div>

                    <div class="flex items-center justify-between mb-4">
                        <span class="px-2 py-1 flex items-center font-semibold text-xs rounded text-yellow-700 bg-yellow-200">On Progress</span>
                        <span class="px-2 py-1 flex items-center font-semibold text-xs rounded text-red-400 border border-red-400  bg-white">Due date: 15-11-2022</span>
                    </div>

                    <div class="relative mb-4">
                        <a href="#">
                            <img class="inline-block rounded-full shadow-xl w-12 h-12 max-w-full ltr:-mr-4 rtl:-ml-4 border-2 bg-gray-300 border-gray-200 transform hover:-translate-y-1"
                                 src="../src/img/avatar/avatar2.png" alt="Image Description">
                        </a>
                        <a href="#">
                            <img class="inline-block rounded-full shadow-xl w-12 h-12 max-w-full ltr:-mr-4 rtl:-ml-4 border-2 bg-gray-300 border-gray-200 transform hover:-translate-y-1"
                                 src="../src/img/avatar/avatar3.png" alt="Image Description">
                        </a>
                        <a href="#">
                            <img class="inline-block rounded-full shadow-xl w-12 h-12 max-w-full ltr:-mr-4 rtl:-ml-4 border-2 bg-gray-300 border-gray-200 transform hover:-translate-y-1"
                                 src="../src/img/avatar/avatar4.png" alt="Image Description">
                        </a>
                        <a href="#">
                            <span class="ltr:ml-5 rtl:mr-5 text-sm text-gray-500 font-semibold self-center">+2 more</span>
                        </a>
                    </div>

                    <div class="w-full h-4 bg-gray-200 rounded-full mt-2">
                        <div class="h-full text-center text-xs text-white bg-yellow-500 rounded-full"
                             style="width:55%">
                            <span class="text-xs text-white text-center">55%</span>
                        </div>
                    </div>

                    <div class="flex justify-between mt-3">
                        <div>
                                    <span class="text-sm inline-block text-gray-500 dark:text-gray-100">Task done : <span
                                            class="text-gray-700 dark:text-white font-bold">26</span>/50</span>
                        </div>
                        <div>
                            <span class="px-2 py-1 text-xs rounded font-semibold text-green-500 bg-green-50">Front End</span>
                            <span class="px-2 py-1 text-xs rounded text-indigo-500 font-semibold bg-indigo-100">UI/UX</span>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}

        </div>

        <div class="flex flex-row justify-between p-4">
            <p class="self-center">Showing 1 to 10 of 33 results</p>
            <nav aria-label="Page navigation">
                <ul x-data="{ item: '1' }" class="flex justify-end space-x-0">
                    <li><a :class="{ 'bg-indigo-500 text-gray-100': item === '1' }" @click="item = '1'"
                           class="ltr:rounded-l rtl:rounded-r block relative py-2 px-4 bg-white border border-gray-200 hover:text-gray-100 hover:bg-indigo-600 ltr:-mr-0.5 rtl:-ml-0.5 dark:bg-gray-800 dark:border-gray-700"
                           href="#">1</a></li>
                    <li><a :class="{ 'bg-indigo-500 text-gray-100': item === '2' }" @click="item = '2'"
                           class="block relative py-2 px-4 bg-white border border-gray-200 hover:text-gray-100 hover:bg-indigo-600 ltr:-mr-0.5 rtl:-ml-0.5 dark:bg-gray-800 dark:border-gray-700"
                           href="#">2</a></li>
                    <li><a :class="{ 'bg-indigo-500 text-gray-100': item === '3' }" @click="item = '3'"
                           class="block relative py-2 px-4 bg-white border border-gray-200 hover:text-gray-100 hover:bg-indigo-600 ltr:-mr-0.5 rtl:-ml-0.5 dark:bg-gray-800 dark:border-gray-700"
                           href="#">3</a></li>
                    <li>
                        <a :class="{ 'bg-indigo-500 text-gray-100': item === '4' }" @click="item = '4'"
                           class="block relative py-2 px-4 bg-white border border-gray-200 hover:text-gray-100 hover:bg-indigo-600 ltr:-mr-0.5 rtl:-ml-0.5 dark:bg-gray-800 dark:border-gray-700 ltr:rounded-r rtl:rounded-l"
                           href="#" aria-label="Next">
                            <span aria-hidden="true">»</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    </div>

{% endblock %}